#!/usr/bin/env php
<?php

use Pho\Console\ConsoleProgram;

require_once __DIR__.'/bootstrap/helpers.php';
require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/bootstrap/app.php';
require_once __DIR__.'/bootstrap/load.php';
require_once __DIR__.'/bootstrap/console.php';

$pho_container = $app->buildContainer();
$app->run(ConsoleProgram::class);
